name: Arief Samuel
job-title: web developer
email: ariefsamuel21@gmail.com
description: >
  Arief Samuel is my name. I am a Web Developer based in Jakarta. I am currently not available for hire.
keywords: arief samuel, C#, Docker, Backend, javascript, html, css, express, web developer, Loyal.Id
baseurl:
url: "https://ariefsamuel.cyou"
linkedin-url: https://www.linkedin.com/in/arief-samuel-6962b91a8/
github-url: https://github.com/arifsamuel
stackoverflow-url: https://stackoverflow.com/users/13529905/arief21
projects-url: https://stackoverflow.com/users/13529905/arief21

# Google webmaster tools
google_verify: Oi_XAR6yGyObqCQyGn7FXJv9sejZSrNxFlQs_M5LsBc

sass:
  style: nested

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Rakefile
